name: TOML/MITRE Validation
# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

jobs:
  toml-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: python development/validation.py
      - run: python development/mitre.py
